### ISSUE TITLE
Vagrant up leads into compile errors

### ISSUE THREAD

**Issue by tobru** [Staffjoy/v2#10]
I know that this project is not active anymore, nevertheless I wan't to report the following issue: After a fresh clone of this repo and a `vagrant up` leads into:

```
[...]
    default: go/test/zerodivide.go
    default: uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant)
    default: ++ sudo mv go /usr/local
    default: ++ sudo rm go1.7.linux-amd64.tar.gz
    default: ++ echo 'export GOPATH=/home/vagrant/golang'
    default: ++ echo 'export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin'
    default: ++ sudo -u vagrant -H bash -c '
    default: id
    default: source ~/.profile
    default: 
    default: if ! command -V golint ; then
    default:     go get -u github.com/golang/lint/golint
    default:     go get -u golang.org/x/tools/cmd/cover
    default:     go get -u golang.org/x/tools/cmd/goimports
    default: fi
    default: 
    default: if ! command -V protoc-gen-go ; then 
    default:     go get -u github.com/golang/protobuf/...
    default:     go get -u github.com/grpc-ecosystem/grpc-gateway/...
    default: fi
    default: 
    default: if ! command -V glide ; then
    default:     curl https://glide.sh/get | sh
    default: fi
    default: 
    default: if ! command -V migrate ; then 
    default:     go get github.com/mattes/migrate
    default: fi
    default: 
    default: if ! command -V buildifier ; then
    default:     go get -d -u github.com/bazelbuild/buildifier/buildifier
    default:     # generate step is why this isn'\''t Glide-able
    default:     go generate github.com/bazelbuild/buildifier/core
    default:     go install github.com/bazelbuild/buildifier/buildifier
    default: fi
    default: 
    default: if ! command -V go-bindata ; then
    default:     go get -u github.com/jteeuwen/go-bindata/...
    default: fi
    default: 
    default: go get -u github.com/gogo/protobuf/...
    default: 
    default: # used for local filesystem watching
    default: if ! command -V modd ; then
    default:     go get github.com/cortesi/modd/cmd/modd
    default: fi
    default: '
    default: bash: line 4: command: golint: not found
    default: bash: line 10: command: protoc-gen-go: not found
    default: # github.com/go-resty/resty
    default: golang/src/github.com/go-resty/resty/middleware.go:31: undefined: url.PathEscape
    default: golang/src/github.com/go-resty/resty/middleware.go:36: undefined: url.PathEscape
    default: go build github.com/grpc-ecosystem/grpc-gateway/examples/integration: no buildable Go source files in /home/vagrant/golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/integration
    default: # github.com/grpc-ecosystem/grpc-gateway/examples/server
    default: golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/server/a_bit_of_everything.go:40: cannot use _ABitOfEverythingServer literal (type *_ABitOfEverythingServer) as type ABitOfEverythingServer in return argument:
    default: 	*_ABitOfEverythingServer does not implement ABitOfEverythingServer (wrong type for Create method)
    default: 		have Create("context".Context, *examplepb.ABitOfEverything) (*examplepb.ABitOfEverything, error)
    default: 		want Create("golang.org/x/net/context".Context, *examplepb.ABitOfEverything) (*examplepb.ABitOfEverything, error)
    default: golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/server/echo.go:17: cannot use new(echoServer) (type *echoServer) as type examplepb.EchoServiceServer in return argument:
    default: 	*echoServer does not implement examplepb.EchoServiceServer (wrong type for Echo method)
    default: 		have Echo("context".Context, *examplepb.SimpleMessage) (*examplepb.SimpleMessage, error)
    default: 		want Echo("golang.org/x/net/context".Context, *examplepb.SimpleMessage) (*examplepb.SimpleMessage, error)
    default: golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/server/flow_combination.go:13: cannot use flowCombinationServer literal (type *flowCombinationServer) as type examplepb.FlowCombinationServer in return argument:
    default: 	*flowCombinationServer does not implement examplepb.FlowCombinationServer (wrong type for RpcBodyRpc method)
    default: 		have RpcBodyRpc("context".Context, *examplepb.NonEmptyProto) (*examplepb.EmptyProto, error)
    default: 		want RpcBodyRpc("golang.org/x/net/context".Context, *examplepb.NonEmptyProto) (*examplepb.EmptyProto, error)
    default: golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/server/responsebody.go:14: cannot use new(responseBodyServer) (type *responseBodyServer) as type examplepb.ResponseBodyServiceServer in return argument:
    default: 	*responseBodyServer does not implement examplepb.ResponseBodyServiceServer (wrong type for GetResponseBody method)
    default: 		have GetResponseBody("context".Context, *examplepb.ResponseBodyIn) (*examplepb.ResponseBodyOut, error)
    default: 		want GetResponseBody("golang.org/x/net/context".Context, *examplepb.ResponseBodyIn) (*examplepb.ResponseBodyOut, error)
    default: golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/server/unannotatedecho.go:16: cannot use new(unannotatedEchoServer) (type *unannotatedEchoServer) as type examplepb.UnannotatedEchoServiceServer in return argument:
    default: 	*unannotatedEchoServer does not implement examplepb.UnannotatedEchoServiceServer (wrong type for Echo method)
    default: 		have Echo("context".Context, *examplepb.UnannotatedSimpleMessage) (*examplepb.UnannotatedSimpleMessage, error)
    default: 		want Echo("golang.org/x/net/context".Context, *examplepb.UnannotatedSimpleMessage) (*examplepb.UnannotatedSimpleMessage, error)
    default: # github.com/grpc-ecosystem/grpc-gateway/examples/gateway
    default: golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/gateway/gateway.go:21: cannot use examplepb.RegisterEchoServiceHandler (type func("golang.org/x/net/context".Context, *runtime.ServeMux, *grpc.ClientConn) error) as type func("context".Context, *runtime.ServeMux, *grpc.ClientConn) error in array or slice literal
    default: golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/gateway/gateway.go:22: cannot use examplepb.RegisterStreamServiceHandler (type func("golang.org/x/net/context".Context, *runtime.ServeMux, *grpc.ClientConn) error) as type func("context".Context, *runtime.ServeMux, *grpc.ClientConn) error in array or slice literal
    default: golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/gateway/gateway.go:23: cannot use examplepb.RegisterABitOfEverythingServiceHandler (type func("golang.org/x/net/context".Context, *runtime.ServeMux, *grpc.ClientConn) error) as type func("context".Context, *runtime.ServeMux, *grpc.ClientConn) error in array or slice literal
    default: golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/gateway/gateway.go:24: cannot use examplepb.RegisterFlowCombinationHandler (type func("golang.org/x/net/context".Context, *runtime.ServeMux, *grpc.ClientConn) error) as type func("context".Context, *runtime.ServeMux, *grpc.ClientConn) error in array or slice literal
    default: golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/gateway/gateway.go:25: cannot use examplepb.RegisterResponseBodyServiceHandler (type func("golang.org/x/net/context".Context, *runtime.ServeMux, *grpc.ClientConn) error) as type func("context".Context, *runtime.ServeMux, *grpc.ClientConn) error in array or slice literal
    default: golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/gateway/main.go:66: s.Shutdown undefined (type *http.Server has no field or method Shutdown)
    default: golang/src/github.com/grpc-ecosystem/grpc-gateway/examples/gateway/main.go:72: undefined: http.ErrServerClosed
    default: bash: line 15: command: glide: not found
    default:  
    default:  
    default: %
    default:  
    default: T
    default: o
    default: t
    default: a
    default: l
    default:  
    default:  
    default:  
    default:  
    default: %
    default:  
    default: R
    default: e
    default: c
    default: e
    default: i
    default: v
    default: e
    default: d
    default:  
    default: %
    default:  
    default: X
    default: f
    default: e
    default: r
    default: d
    default:  
    default:  
    default: Average Speed   Time    Time     Time  Current
    default:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    default:  
    default: 1
    default: 5
    default:  
    default:  
    default: 4
    default: 8
    default: 33   15   743    0     0   1323      0  0:00:03 --:--:--  0:00:03  1322
    default: 100  4833  100  4833    0     0   8031      0 --:--:-- --:--:-- --:--:--  8028
    default: ARCH=amd64
    default: OS=linux
    default: Using curl as download tool
    default: Getting https://glide.sh/version
    default: TAG=v0.13.2
    default: GLIDE_DIST=glide-v0.13.2-linux-amd64.tar.gz
    default: Downloading https://github.com/Masterminds/glide/releases/download/v0.13.2/glide-v0.13.2-linux-amd64.tar.gz
    default: glide version v0.13.2 installed successfully
    default: bash: line 19: command: migrate: not found
    default: bash: line 23: command: buildifier: not found
    default: can't load package: package github.com/bazelbuild/buildifier/core: cannot find package "github.com/bazelbuild/buildifier/core" in any of:
    default: 	/usr/local/go/src/github.com/bazelbuild/buildifier/core (from $GOROOT)
    default: 	/home/vagrant/golang/src/github.com/bazelbuild/buildifier/core (from $GOPATH)
    default: # github.com/bazelbuild/buildtools/build
    default: golang/src/github.com/bazelbuild/buildtools/build/lex.go:740: undefined: sort.SliceStable
    default: bash: line 30: command: go-bindata: not found
    default: bash: line 37: command: modd: not found
    default: # github.com/cortesi/modd/shell
    default: golang/src/github.com/cortesi/modd/shell/shell.go:195: undefined: os.Executable
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Is there anything I could do to get it up and running again? I would love to give Staffjoy a try to see if it could solve some of our issues we currently have with staff scheduling.
